2023-10-12 22:45:07 [info     ] Booting up the Isopalavial Interface
Serving until killed on port 8000...
2023-10-12 22:45:07 [info     ] {"reqHeaders": {"CONTENT-LENGTH": "", "CONTENT-TYPE": "application/x-www-form-urlencoded", "HOST": "localhost:8000", "USER-AGENT": "curl/7.68.0", "X-REQUEST-ID": "healthcheck", "ACCEPT": "text/plain"}, "reqMedia": {}, "status": "200 OK"} method=GET rid=healthcheck time=1697165107.9799023 uri=/healthcheck
2023-10-12 22:45:10 [error    ] Unhandled Exception            method=GET rid=healthcheck time=1697165107.9799023 uri=/healthcheck
Traceback (most recent call last):
  File "falcon/request.py", line 1154, in falcon.request.Request.get_header
KeyError: 'HTTP_X_REQUEST_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "falcon/app.py", line 327, in falcon.app.App.__call__
  File "/home/nmitchell/workspace/rascal-debugging-interview/middleware.py", line 15, in process_request
    rid=req.get_header("X-Request-ID", required=True)
  File "falcon/request.py", line 1170, in falcon.request.Request.get_header
falcon.errors.HTTPMissingHeader: <HTTPMissingHeader: 400 Bad Request>
2023-10-12 22:45:10 [error    ] Unhandled Exception            method=GET rid=healthcheck time=1697165107.9799023 uri=/healthcheck
Traceback (most recent call last):
  File "falcon/request.py", line 1154, in falcon.request.Request.get_header
KeyError: 'HTTP_X_REQUEST_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "falcon/app.py", line 375, in falcon.app.App.__call__
  File "/home/nmitchell/workspace/rascal-debugging-interview/middleware.py", line 27, in process_response
    rid=req.get_header("X-Request-ID", required=True)
  File "falcon/request.py", line 1170, in falcon.request.Request.get_header
falcon.errors.HTTPMissingHeader: <HTTPMissingHeader: 400 Bad Request>
2023-10-12 22:45:10 [info     ] {"reqHeaders": {"CONTENT-LENGTH": "", "CONTENT-TYPE": "application/x-www-form-urlencoded", "HOST": "localhost:8000", "USER-AGENT": "python-requests/2.31.0", "ACCEPT-ENCODING": "gzip, deflate", "ACCEPT": "text/plain", "CONNECTION": "keep-alive", "X-REQUEST-ID": "cbee61f9-e1aa-4a29-8423-8c584137d9f6"}, "reqMedia": {}, "status": "200 OK"} method=GET rid=cbee61f9-e1aa-4a29-8423-8c584137d9f6 time=1697165110.4574533 uri=/diagnostic
2023-10-12 22:45:10 [info     ] {"reqHeaders": {"CONTENT-LENGTH": "0", "CONTENT-TYPE": "application/x-www-form-urlencoded", "HOST": "localhost:8000", "USER-AGENT": "python-requests/2.31.0", "ACCEPT-ENCODING": "gzip, deflate", "ACCEPT": "text/plain", "CONNECTION": "keep-alive", "X-REQUEST-ID": "a2cf7223-ac5a-435e-8fc1-271695bf6012"}, "reqMedia": {}, "status": 405} method=PUT rid=a2cf7223-ac5a-435e-8fc1-271695bf6012 time=1697165110.490115 uri=/cool
2023-10-12 22:45:10 [error    ] Unhandled Exception            method=PUT rid=a1f76780-3e77-4b7f-9c23-660d9e3efab3 time=1697165110.49829 uri=/warp
Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "isopalavial_interface.py", line 31, in on_put
    location = req.json()["location"]
AttributeError: 'Request' object has no attribute 'json'
127.0.0.1 - - [12/Oct/2023 22:45:07] "GET /healthcheck HTTP/1.1" 200 11
127.0.0.1 - - [12/Oct/2023 22:45:10] "GET /diagnostic HTTP/1.1" 400 0
127.0.0.1 - - [12/Oct/2023 22:45:10] "GET /diagnostic HTTP/1.1" 200 18
127.0.0.1 - - [12/Oct/2023 22:45:10] "PUT /cool HTTP/1.1" 405 7
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/app.py", line 369, in falcon.app.App.__call__
  File "falcon/app.py", line 1030, in falcon.app.App._handle_exception
  File "isopalavial_interface.py", line 80, in log_errors
    raise ex
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "isopalavial_interface.py", line 31, in on_put
    location = req.json()["location"]
AttributeError: 'Request' object has no attribute 'json'
2023-10-12 22:45:10 [error    ] Unhandled Exception            method=PUT rid=778e17ca-5fca-48b2-9364-5e47135de2ab time=1697165110.5069404 uri=/warp
Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "isopalavial_interface.py", line 31, in on_put
    location = req.json()["location"]
AttributeError: 'Request' object has no attribute 'json'
127.0.0.1 - - [12/Oct/2023 22:45:10] "PUT /warp HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/app.py", line 369, in falcon.app.App.__call__
  File "falcon/app.py", line 1030, in falcon.app.App._handle_exception
  File "isopalavial_interface.py", line 80, in log_errors
    raise ex
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "isopalavial_interface.py", line 31, in on_put
    location = req.json()["location"]
AttributeError: 'Request' object has no attribute 'json'
2023-10-12 22:45:10 [error    ] Unhandled Exception            method=PUT rid=cc9bbc77-0577-4ae6-9405-c6e4791fc78e time=1697165110.5154767 uri=/warp
Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "isopalavial_interface.py", line 31, in on_put
    location = req.json()["location"]
AttributeError: 'Request' object has no attribute 'json'
127.0.0.1 - - [12/Oct/2023 22:45:10] "PUT /warp HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/app.py", line 369, in falcon.app.App.__call__
  File "falcon/app.py", line 1030, in falcon.app.App._handle_exception
  File "isopalavial_interface.py", line 80, in log_errors
    raise ex
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "isopalavial_interface.py", line 31, in on_put
    location = req.json()["location"]
AttributeError: 'Request' object has no attribute 'json'
